# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibb(a, b):
	return a+b

def fibb_to(limit):
	vals = [1, 1]
	pointer = 2
	while True:
		val = fibb(vals[pointer-2], vals[pointer-1])
		if val > limit:
			break
		vals.append(val)
		pointer += 1

	return vals

even_fibs = filter(lambda x: x % 2 == 0, fibb_to(4000000))
print reduce(lambda x, y: x + y, even_fibs);
